// Copyright (c) Customize+.
// Licensed under the MIT license.

using CustomizePlus.Core.Data;
using Newtonsoft.Json;
using OtterGui.Log;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace CustomizePlus.Core.Services;

public sealed class LocalBoneMetadataService
{
    public const int SupportedSchemaVersion = 1;

    private readonly Logger _logger;
    private readonly Dictionary<string, LocalBoneMetadataEntry> _entries = new(StringComparer.OrdinalIgnoreCase);
    private readonly List<LocalBoneMetadataPackStatus> _packStatuses = new();

    public LocalBoneMetadataService(FilenameService filenameService, Logger logger)
    {
        _logger = logger;
        MetadataDirectory = Path.Combine(filenameService.ConfigDirectory, "bone_metadata");
        Reload();
    }

    public string MetadataDirectory { get; }
    public IReadOnlyDictionary<string, LocalBoneMetadataEntry> Entries => _entries;
    public IReadOnlyList<LocalBoneMetadataPackStatus> PackStatuses => _packStatuses;
    public int LoadedPackCount => _packStatuses.Count(p => p.Loaded);
    public int LoadedEntryCount => _entries.Count;

    public void Reload()
    {
        _entries.Clear();
        _packStatuses.Clear();

        try
        {
            Directory.CreateDirectory(MetadataDirectory);
        }
        catch (Exception ex)
        {
            _logger.Error($"Failed to create local bone metadata directory '{MetadataDirectory}': {ex}");
            _packStatuses.Add(new LocalBoneMetadataPackStatus(
                MetadataDirectory,
                "Local bone metadata",
                false,
                0,
                0,
                [$"Could not create metadata directory: {ex.Message}"]));
            return;
        }

        foreach (var file in Directory.EnumerateFiles(MetadataDirectory, "*.json", SearchOption.TopDirectoryOnly).OrderBy(Path.GetFileName))
            LoadPack(file);

        _logger.Information($"Loaded {LoadedEntryCount} local bone metadata entr{(LoadedEntryCount == 1 ? "y" : "ies")} from {LoadedPackCount} pack{(LoadedPackCount == 1 ? string.Empty : "s")}.");
    }

    public bool TryGetEntry(string boneName, out LocalBoneMetadataEntry entry)
        => _entries.TryGetValue(boneName, out entry!);

    public string GetDisplayName(string boneName)
    {
        var builtInDisplay = BoneData.GetBoneDisplayName(boneName);
        if (BoneData.GetBoneFamily(boneName) != BoneData.BoneFamily.Unknown)
            return builtInDisplay;

        return _entries.TryGetValue(boneName, out var entry) && !string.IsNullOrWhiteSpace(entry.DisplayName)
            ? entry.DisplayName!
            : builtInDisplay;
    }

    public string GetSupportLabel(string boneName)
        => _entries.TryGetValue(boneName, out var entry)
            ? entry.SupportLabel
            : "Unknown/custom";

    public string GetRiskNote(string boneName)
        => _entries.TryGetValue(boneName, out var entry)
            ? entry.EffectiveRiskNote
            : "Unknown/custom bone. Manual/experimental only; not trusted for mirroring, propagation safety, guardrails, BIW, or advanced automation by default.";

    public bool MatchesSearch(string boneName, string search)
    {
        if (string.IsNullOrWhiteSpace(search))
            return true;

        if (BoneData.GetBoneFamily(boneName) != BoneData.BoneFamily.Unknown)
            return false;

        if (!_entries.TryGetValue(boneName, out var entry))
            return false;

        var query = search.Trim();
        if (Matches(entry.DisplayName, query) ||
            Matches(entry.Family, query) ||
            Matches(entry.SupportClass, query) ||
            Matches(entry.RiskNotes, query) ||
            Matches(entry.PackName, query))
        {
            return true;
        }

        return entry.AllowSearchAlias &&
               entry.Aliases.Any(alias =>
                   Matches(alias, query) ||
                   query.Contains(alias, StringComparison.OrdinalIgnoreCase));
    }

    public string CreateStarterPackDraft(IEnumerable<string> boneNames, string? packName = null)
    {
        var names = boneNames
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        var pack = new LocalBoneMetadataPack
        {
            SchemaVersion = SupportedSchemaVersion,
            PackName = string.IsNullOrWhiteSpace(packName) ? "Discovered Unknown Bones Draft" : packName,
            PackAuthor = "Local user",
            Source = "Generated by Customize+ Unknown Bone Workbench",
            Description = "Starter metadata draft for locally discovered unknown/custom bones. All entries remain manual-only and advisory.",
            Entries = names
                .Select(name => new LocalBoneMetadataPackEntry
                {
                    BoneName = name,
                    DisplayName = string.Empty,
                    Family = "Unknown",
                    Aliases = [],
                    SupportClass = "ManualOnly",
                    RiskNotes = "Manual/experimental only. Not trusted for mirroring, propagation safety, guardrails, BIW, or advanced automation by default.",
                    ManualOnly = true,
                    AllowSearchAlias = true,
                    MirrorPartner = string.Empty,
                    ParentOverride = string.Empty
                })
                .ToList()
        };

        return JsonConvert.SerializeObject(pack, Formatting.Indented);
    }

    public string SaveStarterPackDraft(IEnumerable<string> boneNames, string? packName = null)
    {
        Directory.CreateDirectory(MetadataDirectory);
        var path = Path.Combine(MetadataDirectory, $"unknown-bones-draft-{DateTime.Now:yyyyMMdd-HHmmss}.json");
        File.WriteAllText(path, CreateStarterPackDraft(boneNames, packName));
        return path;
    }

    private void LoadPack(string file)
    {
        var fileName = Path.GetFileName(file);
        var messages = new List<string>();
        var ignored = 0;

        try
        {
            var text = File.ReadAllText(file);
            var pack = JsonConvert.DeserializeObject<LocalBoneMetadataPack>(text);
            if (pack == null)
            {
                _packStatuses.Add(FailedStatus(fileName, "Invalid or empty JSON metadata pack."));
                _logger.Warning($"Local bone metadata pack '{file}' was invalid or empty.");
                return;
            }

            var packName = string.IsNullOrWhiteSpace(pack.PackName)
                ? Path.GetFileNameWithoutExtension(file)
                : pack.PackName!;

            if (pack.SchemaVersion != SupportedSchemaVersion)
            {
                _packStatuses.Add(new LocalBoneMetadataPackStatus(
                    fileName,
                    packName,
                    false,
                    0,
                    pack.Entries?.Count ?? 0,
                    [$"Unsupported schemaVersion {pack.SchemaVersion}; expected {SupportedSchemaVersion}."]));
                _logger.Warning($"Local bone metadata pack '{file}' uses unsupported schemaVersion {pack.SchemaVersion}; expected {SupportedSchemaVersion}.");
                return;
            }

            var seenInPack = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var loaded = 0;

            foreach (var rawEntry in pack.Entries ?? [])
            {
                var entry = NormalizeEntry(rawEntry, packName, fileName, messages);
                if (entry == null)
                {
                    ignored++;
                    continue;
                }

                if (!seenInPack.Add(entry.BoneName))
                {
                    ignored++;
                    messages.Add($"Duplicate entry '{entry.BoneName}' ignored within pack.");
                    continue;
                }

                if (_entries.ContainsKey(entry.BoneName))
                {
                    ignored++;
                    messages.Add($"Duplicate entry '{entry.BoneName}' ignored because an earlier pack already supplied it.");
                    continue;
                }

                _entries[entry.BoneName] = entry;
                loaded++;
            }

            _packStatuses.Add(new LocalBoneMetadataPackStatus(fileName, packName, true, loaded, ignored, messages));
            if (messages.Count > 0)
                _logger.Warning($"Local bone metadata pack '{file}' loaded with notes: {string.Join("; ", messages)}");
            else
                _logger.Information($"Local bone metadata pack '{file}' loaded with {loaded} entr{(loaded == 1 ? "y" : "ies")}.");
        }
        catch (Exception ex)
        {
            _packStatuses.Add(FailedStatus(fileName, ex.Message));
            _logger.Error($"Failed to load local bone metadata pack '{file}': {ex}");
        }
    }

    private static LocalBoneMetadataEntry? NormalizeEntry(
        LocalBoneMetadataPackEntry rawEntry,
        string packName,
        string fileName,
        List<string> messages)
    {
        var boneName = rawEntry.EffectiveBoneName?.Trim();
        if (string.IsNullOrWhiteSpace(boneName))
        {
            messages.Add("Entry without boneName/codeName ignored.");
            return null;
        }

        var supportClass = NormalizeSupportClass(rawEntry.SupportClass, boneName, messages);
        var manualOnly = rawEntry.ManualOnly ?? supportClass is "ManualOnly" or "Unknown" or "Risky";
        var aliases = rawEntry.Aliases?
            .Where(alias => !string.IsNullOrWhiteSpace(alias))
            .Select(alias => alias.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray() ?? [];

        return new LocalBoneMetadataEntry(
            boneName,
            TrimToNull(rawEntry.DisplayName),
            TrimToNull(rawEntry.Family),
            aliases,
            supportClass,
            TrimToNull(rawEntry.RiskNotes),
            manualOnly,
            rawEntry.AllowSearchAlias ?? true,
            TrimToNull(rawEntry.MirrorPartner),
            TrimToNull(rawEntry.ParentOverride),
            packName,
            fileName);
    }

    private static LocalBoneMetadataPackStatus FailedStatus(string fileName, string message)
        => new(fileName, Path.GetFileNameWithoutExtension(fileName), false, 0, 0, [message]);

    private static bool Matches(string? value, string query)
        => !string.IsNullOrWhiteSpace(value) && value.Contains(query, StringComparison.OrdinalIgnoreCase);

    private static string NormalizeSupportClass(string? value, string boneName, List<string> messages)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "Unknown";

        var trimmed = value.Trim();
        return trimmed.ToUpperInvariant() switch
        {
            "KNOWNSAFE" => "KnownSafe",
            "KNOWNMODDED" => "KnownModded",
            "MANUALONLY" => "ManualOnly",
            "UNKNOWN" => "Unknown",
            "RISKY" => "Risky",
            _ => UnsupportedSupportClass(trimmed, boneName, messages)
        };
    }

    private static string UnsupportedSupportClass(string value, string boneName, List<string> messages)
    {
        messages.Add($"Entry '{boneName}' has unsupported supportClass '{value}'; normalized to Unknown.");
        return "Unknown";
    }

    private static string? TrimToNull(string? value)
        => string.IsNullOrWhiteSpace(value) ? null : value.Trim();
}
