// Copyright (c) Customize+.
// Licensed under the MIT license.

using CustomizePlus.Core.Data;
using Newtonsoft.Json;
using OtterGui.Log;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace CustomizePlus.Core.Services;

public sealed class LocalBoneMetadataService
{
    public const int SupportedSchemaVersion = 1;

    private readonly Logger _logger;
    private readonly Dictionary<string, LocalBoneMetadataEntry> _entries = new(StringComparer.OrdinalIgnoreCase);
    private readonly List<LocalBoneMetadataPackStatus> _packStatuses = new();

    public LocalBoneMetadataService(FilenameService filenameService, Logger logger)
    {
        _logger = logger;
        MetadataDirectory = Path.Combine(filenameService.ConfigDirectory, "bone_metadata");
        Reload();
    }

    public string MetadataDirectory { get; }
    public IReadOnlyDictionary<string, LocalBoneMetadataEntry> Entries => _entries;
    public IReadOnlyList<LocalBoneMetadataPackStatus> PackStatuses => _packStatuses;
    public int LoadedPackCount => _packStatuses.Count(p => p.Loaded);
    public int LoadedEntryCount => _entries.Count;
    public int TotalPackCount => _packStatuses.Count(p => IsMetadataPackFileName(p.FileName));
    public int IgnoredEntryCount => _packStatuses.Sum(p => p.IgnoredEntryCount);

    public void Reload()
    {
        _entries.Clear();
        _packStatuses.Clear();

        try
        {
            Directory.CreateDirectory(MetadataDirectory);
        }
        catch (Exception ex)
        {
            _logger.Error($"Failed to create local bone metadata directory '{MetadataDirectory}': {ex}");
            _packStatuses.Add(new LocalBoneMetadataPackStatus(
                MetadataDirectory,
                "Local bone metadata",
                false,
                0,
                0,
                [$"Could not create metadata directory: {ex.Message}"]));
            return;
        }

        foreach (var file in Directory.EnumerateFiles(MetadataDirectory, "*.json", SearchOption.TopDirectoryOnly).OrderBy(Path.GetFileName))
            LoadPack(file);

        _logger.Information($"Loaded {LoadedEntryCount} local bone metadata entr{(LoadedEntryCount == 1 ? "y" : "ies")} from {LoadedPackCount} pack{(LoadedPackCount == 1 ? string.Empty : "s")}.");
    }

    public bool TryGetEntry(string boneName, out LocalBoneMetadataEntry entry)
        => _entries.TryGetValue(boneName, out entry!);

    public string GetDisplayName(string boneName)
    {
        var builtInDisplay = BoneData.GetBoneDisplayName(boneName);
        if (BoneData.GetBoneFamily(boneName) != BoneData.BoneFamily.Unknown)
            return builtInDisplay;

        return _entries.TryGetValue(boneName, out var entry) && !string.IsNullOrWhiteSpace(entry.DisplayName)
            ? entry.DisplayName!
            : builtInDisplay;
    }

    public string GetSupportLabel(string boneName)
        => _entries.TryGetValue(boneName, out var entry)
            ? entry.SupportLabel
            : "Unknown/custom";

    public string GetRiskNote(string boneName)
        => _entries.TryGetValue(boneName, out var entry)
            ? entry.EffectiveRiskNote
            : "Unknown/custom bone. Manual/experimental only; not trusted for mirroring, propagation safety, guardrails, BIW, or advanced automation by default.";

    public bool MatchesSearch(string boneName, string search)
    {
        if (string.IsNullOrWhiteSpace(search))
            return true;

        if (BoneData.GetBoneFamily(boneName) != BoneData.BoneFamily.Unknown)
            return false;

        if (!_entries.TryGetValue(boneName, out var entry))
            return false;

        var query = search.Trim();
        if (Matches(entry.DisplayName, query) ||
            Matches(entry.Family, query) ||
            Matches(entry.SupportClass, query) ||
            Matches(entry.RiskNotes, query) ||
            Matches(entry.PackName, query))
        {
            return true;
        }

        return entry.AllowSearchAlias &&
               entry.Aliases.Any(alias =>
                   Matches(alias, query) ||
                   query.Contains(alias, StringComparison.OrdinalIgnoreCase));
    }

    public string CreateStarterPackDraft(IEnumerable<string> boneNames, string? packName = null)
    {
        var names = boneNames
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        var pack = new LocalBoneMetadataPack
        {
            SchemaVersion = SupportedSchemaVersion,
            PackId = "local-unknown-bones-draft",
            PackVersion = "0.1",
            PackName = string.IsNullOrWhiteSpace(packName) ? "Discovered Unknown Bones Draft" : packName,
            PackAuthor = "Local user",
            Source = "Generated by Customize+ Unknown Bone Workbench",
            Description = "Starter metadata draft for locally discovered unknown/custom bones. All entries remain manual-only and advisory.",
            Entries = names
                .Select(name => new LocalBoneMetadataPackEntry
                {
                    BoneName = name,
                    DisplayName = string.Empty,
                    Family = "Unknown",
                    Aliases = [],
                    SupportClass = "ManualOnly",
                    RiskNotes = "Manual/experimental only. Not trusted for mirroring, propagation safety, guardrails, BIW, or advanced automation by default.",
                    ManualOnly = true,
                    AllowSearchAlias = true,
                    MirrorPartner = string.Empty,
                    ParentOverride = string.Empty,
                    CandidateOrigin = "UnknownCustom",
                    CandidateFunctionalRole = "Unknown",
                    CandidateBodyRegion = "Unknown",
                    CandidateAutomationTrust = "ManualOnly",
                    TrustLevel = nameof(LocalBoneMetadataTrust.ManualExtension),
                })
                .ToList()
        };

        return JsonConvert.SerializeObject(pack, Formatting.Indented);
    }

    public string SaveStarterPackDraft(IEnumerable<string> boneNames, string? packName = null)
    {
        Directory.CreateDirectory(MetadataDirectory);
        var path = Path.Combine(MetadataDirectory, $"unknown-bones-draft-{DateTime.Now:yyyyMMdd-HHmmss}.json");
        File.WriteAllText(path, CreateStarterPackDraft(boneNames, packName));
        return path;
    }

    /// <summary>Exports compact observed facts and candidate notes for registry authoring. No runtime state is modified.</summary>
    public string CreateEvidenceExport(SkeletonCapabilityManifest manifest, IEnumerable<UnknownBoneEvidenceRecord> bones)
    {
        var export = new UnknownBoneEvidenceExport(
            SchemaVersion: 1,
            StructuralFingerprint: manifest.StructuralFingerprint,
            Capabilities: manifest.Capabilities,
            Bones: bones.OrderBy(static bone => bone.BoneName, StringComparer.Ordinal).ToArray(),
            GeneratedBy: "Customize+ Unknown Bone Workbench");
        return JsonConvert.SerializeObject(export, Formatting.Indented);
    }

    public bool CanDeletePackFile(string fileName)
        => TryGetValidatedPackPath(fileName, out _, out _);

    public bool TryDeletePackFile(string fileName, out string message)
    {
        if (!TryGetValidatedPackPath(fileName, out var path, out message))
            return false;

        try
        {
            if (!File.Exists(path))
            {
                message = $"Metadata pack '{fileName}' no longer exists.";
                Reload();
                return false;
            }

            File.Delete(path);
            message = $"Deleted metadata pack '{fileName}'.";
            Reload();
            return true;
        }
        catch (Exception ex)
        {
            message = $"Could not delete metadata pack '{fileName}': {ex.Message}";
            _logger.Error($"Could not delete local bone metadata pack '{path}': {ex}");
            return false;
        }
    }

    private void LoadPack(string file)
    {
        var fileName = Path.GetFileName(file);
        var messages = new List<string>();
        var ignored = 0;

        try
        {
            var text = File.ReadAllText(file);
            var pack = JsonConvert.DeserializeObject<LocalBoneMetadataPack>(text);
            if (pack == null)
            {
                _packStatuses.Add(FailedStatus(fileName, "Invalid or empty JSON metadata pack."));
                _logger.Warning($"Local bone metadata pack '{file}' was invalid or empty.");
                return;
            }

            var packName = string.IsNullOrWhiteSpace(pack.PackName)
                ? Path.GetFileNameWithoutExtension(file)
                : pack.PackName!;

            if (pack.SchemaVersion != SupportedSchemaVersion)
            {
                _packStatuses.Add(new LocalBoneMetadataPackStatus(
                    fileName,
                    packName,
                    false,
                    0,
                    pack.Entries?.Count ?? 0,
                    [$"Unsupported schemaVersion {pack.SchemaVersion}; expected {SupportedSchemaVersion}."]));
                _logger.Warning($"Local bone metadata pack '{file}' uses unsupported schemaVersion {pack.SchemaVersion}; expected {SupportedSchemaVersion}.");
                return;
            }

            var seenInPack = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var loaded = 0;

            foreach (var rawEntry in pack.Entries ?? [])
            {
                var entry = NormalizeEntry(rawEntry, packName, fileName, messages);
                if (entry == null)
                {
                    ignored++;
                    continue;
                }

                if (!seenInPack.Add(entry.BoneName))
                {
                    ignored++;
                    messages.Add($"Duplicate entry '{entry.BoneName}' ignored within pack.");
                    continue;
                }

                if (BoneData.GetBoneFamily(entry.BoneName) != BoneData.BoneFamily.Unknown)
                {
                    ignored++;
                    messages.Add($"Entry '{entry.BoneName}' ignored because built-in curated metadata remains authoritative.");
                    continue;
                }

                var duplicateAlias = entry.Aliases.FirstOrDefault(alias => _entries.Values.Any(existing => existing.Aliases.Contains(alias, StringComparer.OrdinalIgnoreCase)));
                if (duplicateAlias != null)
                {
                    ignored++;
                    messages.Add($"Entry '{entry.BoneName}' ignored because alias '{duplicateAlias}' is already supplied by an earlier pack.");
                    continue;
                }

                if (_entries.ContainsKey(entry.BoneName))
                {
                    ignored++;
                    messages.Add($"Duplicate entry '{entry.BoneName}' ignored because an earlier pack already supplied it.");
                    continue;
                }

                _entries[entry.BoneName] = entry;
                loaded++;
            }

            _packStatuses.Add(new LocalBoneMetadataPackStatus(fileName, packName, true, loaded, ignored, messages));
            if (messages.Count > 0)
                _logger.Warning($"Local bone metadata pack '{file}' loaded with notes: {string.Join("; ", messages)}");
            else
                _logger.Information($"Local bone metadata pack '{file}' loaded with {loaded} entr{(loaded == 1 ? "y" : "ies")}.");
        }
        catch (Exception ex)
        {
            _packStatuses.Add(FailedStatus(fileName, ex.Message));
            _logger.Error($"Failed to load local bone metadata pack '{file}': {ex}");
        }
    }

    private static LocalBoneMetadataEntry? NormalizeEntry(
        LocalBoneMetadataPackEntry rawEntry,
        string packName,
        string fileName,
        List<string> messages)
    {
        var boneName = rawEntry.EffectiveBoneName?.Trim();
        if (string.IsNullOrWhiteSpace(boneName))
        {
            messages.Add("Entry without boneName/codeName ignored.");
            return null;
        }

        var supportClass = NormalizeSupportClass(rawEntry.SupportClass, boneName, messages);
        var manualOnly = rawEntry.ManualOnly ?? supportClass is "ManualOnly" or "Unknown" or "Risky";
        var aliases = rawEntry.Aliases?
            .Where(alias => !string.IsNullOrWhiteSpace(alias))
            .Select(alias => alias.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray() ?? [];

        var mirror = TrimToNull(rawEntry.MirrorPartner);
        if (string.Equals(mirror, boneName, StringComparison.OrdinalIgnoreCase))
        {
            messages.Add($"Entry '{boneName}' mirrors itself; mirror candidate ignored.");
            mirror = null;
        }
        var parent = TrimToNull(rawEntry.ParentOverride);
        if (string.Equals(parent, boneName, StringComparison.OrdinalIgnoreCase))
        {
            messages.Add($"Entry '{boneName}' parents itself; parent candidate ignored.");
            parent = null;
        }

        var trust = NormalizeTrust(rawEntry.TrustLevel, boneName, messages);
        // Local candidate declarations are documentation only.  Keep unsafe declarations manual by default.
        if (!manualOnly && trust != LocalBoneMetadataTrust.LocallyTrusted)
        {
            manualOnly = true;
            messages.Add($"Entry '{boneName}' was kept manual-only because local metadata is advisory.");
        }

        return new LocalBoneMetadataEntry(
            boneName,
            TrimToNull(rawEntry.DisplayName),
            TrimToNull(rawEntry.Family),
            aliases,
            supportClass,
            TrimToNull(rawEntry.RiskNotes),
            manualOnly,
            rawEntry.AllowSearchAlias ?? true,
            mirror,
            parent,
            TrimToNull(rawEntry.CandidateOrigin),
            TrimToNull(rawEntry.CandidateFunctionalRole),
            TrimToNull(rawEntry.CandidateBodyRegion),
            TrimToNull(rawEntry.CandidateCapability),
            TrimToNull(rawEntry.CandidateAxisMapping),
            TrimToNull(rawEntry.CandidateScalingInheritance),
            TrimToNull(rawEntry.CandidateAutomationTrust),
            trust,
            packName,
            fileName);
    }

    private static LocalBoneMetadataPackStatus FailedStatus(string fileName, string message)
        => new(fileName, Path.GetFileNameWithoutExtension(fileName), false, 0, 0, [message]);

    private bool TryGetValidatedPackPath(string fileName, out string path, out string message)
    {
        path = string.Empty;
        message = string.Empty;

        if (!IsMetadataPackFileName(fileName))
        {
            message = "Only local .json metadata pack files can be deleted.";
            return false;
        }

        var root = Path.GetFullPath(MetadataDirectory);
        var candidate = Path.GetFullPath(Path.Combine(root, fileName));
        var relative = Path.GetRelativePath(root, candidate);
        if (relative.StartsWith("..", StringComparison.Ordinal) || Path.IsPathRooted(relative))
        {
            message = "Refusing to delete a file outside the local bone metadata folder.";
            return false;
        }

        path = candidate;
        return true;
    }

    private static bool IsMetadataPackFileName(string fileName)
        => !string.IsNullOrWhiteSpace(fileName) &&
           string.Equals(Path.GetFileName(fileName), fileName, StringComparison.Ordinal) &&
           string.Equals(Path.GetExtension(fileName), ".json", StringComparison.OrdinalIgnoreCase);

    private static bool Matches(string? value, string query)
        => !string.IsNullOrWhiteSpace(value) && value.Contains(query, StringComparison.OrdinalIgnoreCase);

    private static string NormalizeSupportClass(string? value, string boneName, List<string> messages)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "Unknown";

        var trimmed = value.Trim();
        return trimmed.ToUpperInvariant() switch
        {
            "KNOWNSAFE" => "KnownSafe",
            "KNOWNMODDED" => "KnownModded",
            "MANUALONLY" => "ManualOnly",
            "UNKNOWN" => "Unknown",
            "RISKY" => "Risky",
            _ => UnsupportedSupportClass(trimmed, boneName, messages)
        };
    }

    private static string UnsupportedSupportClass(string value, string boneName, List<string> messages)
    {
        messages.Add($"Entry '{boneName}' has unsupported supportClass '{value}'; normalized to Unknown.");
        return "Unknown";
    }

    private static LocalBoneMetadataTrust NormalizeTrust(string? value, string boneName, List<string> messages)
    {
        if (string.IsNullOrWhiteSpace(value))
            return LocalBoneMetadataTrust.Informational;

        if (Enum.TryParse<LocalBoneMetadataTrust>(value.Trim(), true, out var parsed))
            return parsed;

        messages.Add($"Entry '{boneName}' has unsupported trustLevel '{value}'; normalized to Informational.");
        return LocalBoneMetadataTrust.Informational;
    }

    private static string? TrimToNull(string? value)
        => string.IsNullOrWhiteSpace(value) ? null : value.Trim();
}
